name: spotbuy
description: A new Flutter project.

# JThe following line prevents the package from being accidentally published to
# Apub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# YThe following defines the version and build number for your application.
# RA version number is three numbers separated by dots, like 1.2.43
# Afollowed by an optional build number separated by a +.
# VBoth the version and the builder number may be overridden in flutter
# Ibuild by specifying --build-name and --build-number, respectively.
# RIn Android, build-name is used as versionName while build-number used as versionCode.
# ARead more about Android versioning at https://https://bit.ly/3HmowF3/developer.android.com/studio/publish/versioning
# JIn iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# DRead more about iOS versioning at
# Ehttps://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

# ODependencies specify other packages that your package needs in order to work.
# RTo automatically upgrade your package dependencies to the latest versions
# Econsider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_search_bar: ^2.1.0
  flutter_local_notifications: ^9.4.1
  open_file: ^3.2.1
  file_picker: ^4.5.1
  flutter_chat_ui: ^1.5.8
  url_launcher: ^6.0.20
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.0
  change_app_package_name: ^1.0.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.6
  firebase_storage_web: ^3.2.6
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_launcher_name: ^0.0.1
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^9.2.0
  geocoding: ^2.0.2
  geolocator: ^8.1.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  google_fonts: ^2.3.1
  month_year_picker: ^0.1.0+1
  multi_image_picker2: ^5.0.2
  photo_view: ^0.13.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  share_plus: ^4.0.4

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: 'SpotBuy'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SEGOEUI
      fonts:
        - asset: assets/fonts/SegoeUI/SEGOEUI.TTF
        - asset: assets/fonts/SegoeUI/SEGOEUIB.TTF
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
